import type { ScreeningStageConfig } from './types'

// Sum of weights = 1.25 — normalized in scoring.ts (divide by WEIGHT_SUM)
export const WEIGHT_SUM = 1.25
export const SCREENING_STAGES: ScreeningStageConfig[] = [

  // ══ STAGE 1 — Letter Confusion ══
  {
    id: 'letter_confusion', nameAr: 'تمييز الحروف المتشابهة',
    nameEn: 'Letter Confusion', descriptionAr: 'استمع للحرف واضغط عليه',
    weight: 0.10, maxRawScore: 12,
    questions: [
      { id: 'lc_01', stageId: 'letter_confusion', audioPrompt: 'باء',
        displayArabic: 'الحرف: ب', displayOptions: ['ب','ت','ث','ن'],
        correctIndex: 0, timeLimitSeconds: 25, difficultyWeight: 1.0 },
      { id: 'lc_02', stageId: 'letter_confusion', audioPrompt: 'حاء',
        displayArabic: 'الحرف: ح', displayOptions: ['ج','ح','خ'],
        correctIndex: 1, timeLimitSeconds: 25, difficultyWeight: 1.0 },
      { id: 'lc_03', stageId: 'letter_confusion', audioPrompt: 'ذال',
        displayArabic: 'الحرف: ذ', displayOptions: ['د','ذ','ر','ز'],
        correctIndex: 1, timeLimitSeconds: 25, difficultyWeight: 1.0 },
      { id: 'lc_04', stageId: 'letter_confusion', audioPrompt: 'شين',
        displayArabic: 'الحرف: ش', displayOptions: ['س','ش','ص','ض'],
        correctIndex: 1, timeLimitSeconds: 25, difficultyWeight: 1.0 },
      { id: 'lc_05', stageId: 'letter_confusion', audioPrompt: 'غين',
        displayArabic: 'الحرف: غ', displayOptions: ['ع','غ'],
        correctIndex: 1, timeLimitSeconds: 25, difficultyWeight: 1.0 },
      { id: 'lc_06', stageId: 'letter_confusion', audioPrompt: 'ثاب',
        displayArabic: 'الكلمة: ثَاب', displayOptions: ['بَاب','تَاب','ثَاب','نَاب'],
        correctIndex: 2, timeLimitSeconds: 20, difficultyWeight: 1.5 },
      { id: 'lc_07', stageId: 'letter_confusion', audioPrompt: 'سَمِع',
        displayArabic: 'الكلمة: سَمِع', displayOptions: ['سَمِع','شَمِع','صَمِع','سَمَع'],
        correctIndex: 0, timeLimitSeconds: 20, difficultyWeight: 1.5 },
    ],
  },

  // ══ STAGE 2 — RAN ══ (strongest Arabic predictor)
  {
    id: 'ran', nameAr: 'التسمية السريعة', nameEn: 'Rapid Naming',
    descriptionAr: 'اضغط على اسم الحرف أو الرقم بأسرع ما تستطيع',
    weight: 0.25, maxRawScore: 16,
    questions: [
      { id: 'ran_01', stageId: 'ran', displayArabic: 'ب',
        displayOptions: ['باء','تاء','نون','ياء'],
        correctIndex: 0, timeLimitSeconds: 8, difficultyWeight: 1.0 },
      { id: 'ran_02', stageId: 'ran', displayArabic: 'س',
        displayOptions: ['شين','سين','صاد','ضاد'],
        correctIndex: 1, timeLimitSeconds: 8, difficultyWeight: 1.0 },
      { id: 'ran_03', stageId: 'ran', displayArabic: 'ع',
        displayOptions: ['غين','عين','حاء','خاء'],
        correctIndex: 1, timeLimitSeconds: 8, difficultyWeight: 1.0 },
      { id: 'ran_04', stageId: 'ran', displayArabic: '٧',
        displayOptions: ['٥','٦','٧','٨'],
        correctIndex: 2, timeLimitSeconds: 6, difficultyWeight: 1.0 },
      { id: 'ran_05', stageId: 'ran', displayArabic: '٣',
        displayOptions: ['١','٢','٣','٤'],
        correctIndex: 2, timeLimitSeconds: 6, difficultyWeight: 1.0 },
      { id: 'ran_06', stageId: 'ran', displayArabic: 'ق',
        displayOptions: ['فاء','قاف','كاف','لام'],
        correctIndex: 1, timeLimitSeconds: 8, difficultyWeight: 1.0 },
      { id: 'ran_07', stageId: 'ran', displayArabic: 'ظ',
        displayOptions: ['ظاء','طاء','ذال','ثاء'],
        correctIndex: 0, timeLimitSeconds: 8, difficultyWeight: 1.5 },
      { id: 'ran_08', stageId: 'ran', displayArabic: '٩',
        displayOptions: ['٦','٧','٨','٩'],
        correctIndex: 3, timeLimitSeconds: 6, difficultyWeight: 1.0 },
    ],
  },

  // ══ STAGE 3 — Phonological Awareness ══
  {
    id: 'phonological_awareness', nameAr: 'الوعي الصوتي',
    nameEn: 'Phonological Awareness', descriptionAr: 'استمع ثم اختر الإجابة الصحيحة',
    weight: 0.25, maxRawScore: 18,
    questions: [
      { id: 'pa_01', stageId: 'phonological_awareness',
        audioPrompt: 'أي كلمة تقافي كلمة باب',
        displayArabic: 'ما الكلمة التي تُقافي "بَاب"؟',
        displayOptions: ['كِتَاب','ثَوَاب','شَجَرَة','قَلَم'],
        correctIndex: 1, timeLimitSeconds: 30, difficultyWeight: 1.0 },
      { id: 'pa_02', stageId: 'phonological_awareness',
        audioPrompt: 'كم عدد المقاطع في كلمة مدرسة',
        displayArabic: 'كم عدد مقاطع "مَدْرَسَة"؟',
        displayOptions: ['2','3','4','5'],
        correctIndex: 2, timeLimitSeconds: 30, difficultyWeight: 1.0 },
      { id: 'pa_03', stageId: 'phonological_awareness',
        audioPrompt: 'أي كلمة تقافي كلمة نور',
        displayArabic: 'ما الكلمة التي تُقافي "نُور"؟',
        displayOptions: ['سُور','بَيْت','قَلَم','كِتَاب'],
        correctIndex: 0, timeLimitSeconds: 30, difficultyWeight: 1.0 },
      { id: 'pa_04', stageId: 'phonological_awareness',
        audioPrompt: 'قل كلمة سمك بدون صوت سَ',
        displayArabic: '"سَمَك" بدون "سَ" = ؟',
        displayOptions: ['مَك','سَمَ','كَس','سَك'],
        correctIndex: 0, timeLimitSeconds: 30, difficultyWeight: 2.0 },
      { id: 'pa_05', stageId: 'phonological_awareness',
        audioPrompt: 'قل كلمة باب بدون الباء الأولى',
        displayArabic: '"بَاب" بدون "بَـ" الأولى = ؟',
        displayOptions: ['اب','بَا','بَب','آب'],
        correctIndex: 0, timeLimitSeconds: 30, difficultyWeight: 2.0 },
      { id: 'pa_06', stageId: 'phonological_awareness',
        audioPrompt: 'كم عدد المقاطع في كلمة استغفار',
        displayArabic: 'كم عدد مقاطع "اسْتِغْفَار"؟',
        displayOptions: ['3','4','5','6'],
        correctIndex: 1, timeLimitSeconds: 30, difficultyWeight: 1.5 },
    ],
  },

  // ══ STAGE 4 — Pseudowords ══
  {
    id: 'pseudowords', nameAr: 'الكلمات الوهمية', nameEn: 'Pseudoword Reading',
    descriptionAr: 'استمع للكلمة غير الحقيقية واختر مكتوبتها',
    weight: 0.20, maxRawScore: 12,
    questions: [
      { id: 'pw_01', stageId: 'pseudowords', audioPrompt: 'بَتِيل',
        displayArabic: 'اختر الكلمة التي سمعتها (بتشكيل)',
        displayOptions: ['بَتِيل','تَبِيل','بَلِيت','تَلِيب'],
        correctIndex: 0, timeLimitSeconds: 20, difficultyWeight: 1.0 },
      { id: 'pw_02', stageId: 'pseudowords', audioPrompt: 'فِرْبَاس',
        displayArabic: 'اختر الكلمة التي سمعتها (بتشكيل)',
        displayOptions: ['فِرْسَاب','فِرْبَاس','سِرْفَاب','فِبْرَاس'],
        correctIndex: 1, timeLimitSeconds: 20, difficultyWeight: 1.0 },
      { id: 'pw_03', stageId: 'pseudowords', audioPrompt: 'مَلْفِير',
        displayArabic: 'اختر الكلمة التي سمعتها (بدون تشكيل)',
        displayOptions: ['ملفير','مفلير','لمفير','ملفري'],
        correctIndex: 0, timeLimitSeconds: 20, difficultyWeight: 2.0 },
      { id: 'pw_04', stageId: 'pseudowords', audioPrompt: 'تِرْبَاق',
        displayArabic: 'اختر الكلمة التي سمعتها (بدون تشكيل)',
        displayOptions: ['ترباق','تربقا','بترقا','قرتاب'],
        correctIndex: 0, timeLimitSeconds: 20, difficultyWeight: 2.0 },
      { id: 'pw_05', stageId: 'pseudowords', audioPrompt: 'نَشْتُوف',
        displayArabic: 'اختر الكلمة التي سمعتها (بتشكيل)',
        displayOptions: ['نَشْتُوف','شَنْتُوف','نَتْشُوف','شَتْنُوف'],
        correctIndex: 0, timeLimitSeconds: 20, difficultyWeight: 1.0 },
    ],
  },

  // ══ STAGE 5 — Working Memory ══
  // Special: two-phase (show -> recall). correctIndex = -1 (ignored).
  // Correct sequence = displayArabic.split(' — ')
  {
    id: 'working_memory', nameAr: 'الذاكرة العاملة', nameEn: 'Working Memory',
    descriptionAr: 'احفظ الحروف ثم اضغط عليها بنفس الترتيب',
    weight: 0.05, maxRawScore: 10,
    questions: [
      { id: 'wm_01', stageId: 'working_memory',
        displayArabic: 'ب — س — ر',
        displayOptions: ['ب','س','ر','م','ل','ك'],
        correctIndex: -1, timeLimitSeconds: 45, difficultyWeight: 1.0 },
      { id: 'wm_02', stageId: 'working_memory',
        displayArabic: 'م — ل — ك — ب',
        displayOptions: ['م','ل','ك','ب','س','ر','ن'],
        correctIndex: -1, timeLimitSeconds: 45, difficultyWeight: 1.5 },
      { id: 'wm_03', stageId: 'working_memory',
        displayArabic: 'ق — ر — ط — م — ن',
        displayOptions: ['ق','ر','ط','م','ن','س','ل','ك'],
        correctIndex: -1, timeLimitSeconds: 45, difficultyWeight: 2.0 },
    ],
  },

  // ══ STAGE 6 — Vowel Effect ══ (Arabic-only)
  // Pairs: _a = vowelized (baseline), _b = unvowelized (diagnostic)
  // Key metric = delta reaction time between _a and _b
  {
    id: 'vowel_effect', nameAr: 'أثر التشكيل', nameEn: 'Vowel Effect',
    descriptionAr: 'استمع للكلمة واختر مكتوبتها',
    weight: 0.10, maxRawScore: 10,
    questions: [
      { id: 've_01a', stageId: 'vowel_effect', audioPrompt: 'كَتَبَ',
        displayArabic: 'اختر الكلمة الصحيحة (بتشكيل)',
        displayOptions: ['كَتَبَ','كَتَمَ','كَذَبَ','كَلَبَ'],
        correctIndex: 0, timeLimitSeconds: 25, difficultyWeight: 1.0 },
      { id: 've_01b', stageId: 'vowel_effect', audioPrompt: 'كَتَبَ',
        displayArabic: 'اختر الكلمة الصحيحة (بدون تشكيل)',
        displayOptions: ['كتب','كتم','كذب','كلب'],
        correctIndex: 0, timeLimitSeconds: 25, difficultyWeight: 2.0 },
      { id: 've_02a', stageId: 'vowel_effect', audioPrompt: 'ذَهَبَ',
        displayArabic: 'اختر الكلمة الصحيحة (بتشكيل)',
        displayOptions: ['ذَهَبَ','ذَهَلَ','ذَهَنَ','زَهَبَ'],
        correctIndex: 0, timeLimitSeconds: 25, difficultyWeight: 1.0 },
      { id: 've_02b', stageId: 'vowel_effect', audioPrompt: 'ذَهَبَ',
        displayArabic: 'اختر الكلمة الصحيحة (بدون تشكيل)',
        displayOptions: ['ذهب','ذهل','زهب','دهب'],
        correctIndex: 0, timeLimitSeconds: 25, difficultyWeight: 2.0 },
    ],
  },

  // ══ STAGE 7 — Visual Attention ══
  // correctIndex = position of the odd-one-out in the grid
  {
    id: 'visual_attention', nameAr: 'الانتباه البصري', nameEn: 'Visual Attention',
    descriptionAr: 'اضغط على الحرف المختلف في المجموعة',
    weight: 0.05, maxRawScore: 8,
    questions: [
      { id: 'va_01', stageId: 'visual_attention',
        displayArabic: 'أي حرف مختلف؟',
        displayOptions: ['ب','ب','ت','ب','ب'],
        correctIndex: 2, timeLimitSeconds: 20, difficultyWeight: 1.0 },
      { id: 'va_02', stageId: 'visual_attention',
        displayArabic: 'أي حرف مختلف؟',
        displayOptions: ['س','س','س','ش','س','س'],
        correctIndex: 3, timeLimitSeconds: 20, difficultyWeight: 1.0 },
      { id: 'va_03', stageId: 'visual_attention',
        displayArabic: 'أي حرف مختلف؟',
        displayOptions: ['ع','ع','ع','ع','غ','ع'],
        correctIndex: 4, timeLimitSeconds: 15, difficultyWeight: 1.5 },
      { id: 'va_04', stageId: 'visual_attention',
        displayArabic: 'أي حرف مختلف؟',
        displayOptions: ['ق','ق','ف','ق','ق','ق'],
        correctIndex: 2, timeLimitSeconds: 15, difficultyWeight: 1.5 },
    ],
  },

  // ══ STAGE 8 — Morphology ══ (Arabic-only — no Dytective equivalent)
  {
    id: 'morphology', nameAr: 'الوعي الصرفي والجذر',
    nameEn: 'Morphological Awareness',
    descriptionAr: 'اختر الجذر المشترك أو الكلمة من نفس الجذر',
    weight: 0.15, maxRawScore: 16,
    questions: [
      { id: 'mo_01', stageId: 'morphology',
        audioPrompt: 'ما الجذر المشترك في كَتَبَ كِتَاب مَكْتُوب كَاتِب',
        displayArabic: 'الجذر المشترك في: كَتَبَ / كِتَاب / مَكْتُوب / كَاتِب',
        displayOptions: ['ك ت ب','ك ت م','ك ب ر','ت ب ك'],
        correctIndex: 0, timeLimitSeconds: 35, difficultyWeight: 2.0 },
      { id: 'mo_02', stageId: 'morphology',
        audioPrompt: 'أي كلمة من نفس جذر دَرَسَ',
        displayArabic: 'أي كلمة من نفس جذر "دَرَسَ"؟',
        displayOptions: ['مَدْرَسَة','مَكْتَبَة','مَلْعَب','مَطْبَخ'],
        correctIndex: 0, timeLimitSeconds: 25, difficultyWeight: 1.5 },
      { id: 'mo_03', stageId: 'morphology',
        audioPrompt: 'ما الجذر المشترك في سَمِعَ سَمَاع مِسْمَع',
        displayArabic: 'الجذر المشترك في: سَمِعَ / سَمَاع / مِسْمَع',
        displayOptions: ['س م ع','س م ح','س م ك','ص م ع'],
        correctIndex: 0, timeLimitSeconds: 35, difficultyWeight: 2.0 },
      { id: 'mo_04', stageId: 'morphology',
        audioPrompt: 'أي كلمة من نفس جذر عَلِمَ',
        displayArabic: 'أي كلمة من نفس جذر "عَلِمَ"؟',
        displayOptions: ['مَعْلَم','مَكْتَب','مَسْجِد','مَلْعَب'],
        correctIndex: 0, timeLimitSeconds: 25, difficultyWeight: 1.5 },
      { id: 'mo_05', stageId: 'morphology',
        audioPrompt: 'أي كلمة على وزن فاعل',
        displayArabic: 'أي كلمة على وزن "فَاعِل"؟',
        displayOptions: ['كَاتِب','مَكْتُوب','كِتَاب','كَتْب'],
        correctIndex: 0, timeLimitSeconds: 35, difficultyWeight: 2.0 },
    ],
  },

  // ══ STAGE 9 — Letter Position Forms ══ (Arabic-only)
  // Arabic letters have 4 forms: initial / medial / final / isolated
  {
    id: 'letter_position', nameAr: 'شكل الحرف حسب موضعه',
    nameEn: 'Letter Position Forms',
    descriptionAr: 'اختر الشكل الصحيح للحرف حسب موضعه في الكلمة',
    weight: 0.10, maxRawScore: 10,
    questions: [
      { id: 'lp_01', stageId: 'letter_position',
        audioPrompt: 'حرف عين في وسط الكلمة أي شكل صحيح',
        displayArabic: '"ع" في وَسَط الكلمة — أي شكل صحيح؟',
        displayOptions: ['عـ','ـعـ','ـع','ع'],
        correctIndex: 1, timeLimitSeconds: 25, difficultyWeight: 2.0 },
      { id: 'lp_02', stageId: 'letter_position',
        audioPrompt: 'حرف عين في آخر الكلمة أي شكل صحيح',
        displayArabic: '"ع" في آخر الكلمة — أي شكل صحيح؟',
        displayOptions: ['عـ','ـعـ','ـع','ع'],
        correctIndex: 2, timeLimitSeconds: 25, difficultyWeight: 2.0 },
      { id: 'lp_03', stageId: 'letter_position',
        audioPrompt: 'في أي كلمة حرف الحاء في البداية',
        displayArabic: 'في أي كلمة حرف "ح" في البداية؟',
        displayOptions: ['صَحِيح','حَجَر','نَاجِح','رَاحَة'],
        correctIndex: 1, timeLimitSeconds: 25, difficultyWeight: 1.5 },
      { id: 'lp_04', stageId: 'letter_position',
        audioPrompt: 'أكمل كلمة كتاب الحرف الناقص في الوسط',
        displayArabic: 'أكمل: "كـ_ـاب" — الحرف الناقص؟',
        displayOptions: ['ت','ب','ث','ن'],
        correctIndex: 0, timeLimitSeconds: 20, difficultyWeight: 1.5 },
    ],
  },
]

export const TOTAL_STAGES = SCREENING_STAGES.length  // 9

export function getStageByIndex(i: number) { return SCREENING_STAGES[i] ?? null }
export function getStageById(id: string) { return SCREENING_STAGES.find(s => s.id === id) ?? null }
export function getStageNumber(id: string) { return SCREENING_STAGES.findIndex(s => s.id === id) + 1 }
